#! /bin/sh

bspc monitor -d a b c

bspc config border_width         4
bspc config window_gap          12

bspc config focused_border_color "#6699CC"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config initial_polarity first_child

bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bpsc config pointer_action1 move
bpsc config pointer_action3 resize_side

bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off

polybar top --reload --config=$HOME/.config/polybar/config &

