#! /bin/sh

bspc monitor -d a b c

bspc config border_width         4
bspc config window_gap          12

bspc config focused_border_color "#6699CC"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focus_follows_pointer true
-
bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off

bspc config external_rules_command ~/.config/bspwm/pseudo_automatic_mode

polybar top --reload --config=$HOME/.config/polybar/config &

