#!/bin/bash

CHAIN=$1
START=$2
END=$3

old_color=$(bspc config focused_border_color)

while :; do
  while read -r message; do
    echo $message
    if [[ ${message:0:1} == "B" ]]; then
      old_color=$(bspc config focused_border_color)
      bspc config focused_border_color "#C594C5"
    fi

    if [[ "${message:1}" = $CHAIN ]]; then
      echo $START
    fi

    if [[ ${message:0:1} == "E" ]]; then
      bspc config focused_border_color "$old_color"
    fi
  done < "$HOME/.config/sxhkd/fifo"
done

